### ISSUE TITLE
No music found

### ISSUE THREAD

**Issue by SteveOliverC** [SimonRemote/simon-pebble#2]
Mac app on Mavericks shows 1 connected

Enabled SimonRemote in System Prefs for accessibility (assistive apps)

Verified the Pebble App on iPhone 6 Plus is in the foreground

App on Pebble shows "No music found." 

Tried doing a refresh on the Pebble app.

Suggestions?

**Comment by tyhoff** [comment]
Fixing soon.

**Comment by tyhoff** [comment]
dup of #1

**Comment by tyhoff** [comment]
Try these steps. 

Right click on SimonRemote.app and click View Package Contents. 
Go into Contents->Resources and double click on iTunes-info. Run that Script when iTunes is running. 

Does it print out valid information at the bottom?
